---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Chart.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: app
  name: {{ .Release.Name }}
spec:
  ports:
    - port: 8080
      targetPort: 5000
  selector:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    component: app
  type: ClusterIP
